sz002401:
  - buy_price: 13.190
    alert_up: 15
    alert_down: 11
    alert_msg:
      wechat: 1a0a39b1-5c97-4b0b-92e4-c8ca3261d041
      content: "你设置的警戒线到了"
sh588000:
  - buy_price: 1.440
    alert_up: 1.5
    alert_down: 1.2
    alert_msg:
      wechat: 1a0a39b1-5c97-4b0b-92e4-c8ca3261d041
      content: "你设置的警戒线到了"
sz000725:
  - buy_price: 6.55
    alert_up: 8.00
    alert_down: 6
    alert_msg:
      wechat: 1a0a39b1-5c97-4b0b-92e4-c8ca3261d041
      content: "你设置的警戒线到了"
  - want_buy_price: 6.1
    alert_msg:
      wechat: 1a0a39b1-5c97-4b0b-92e4-c8ca3261d041
      content: "已经到了你心目中价位了"